spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/tomxi/spring-config.git
          search-paths: respo
          username: 30260081@qq.com
          password: a110120119

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/