spring:
  profiles:
    active: dev
  application:
    name: hello-spring-cloud-admin
  config:
    uri: http://localhost:8888
    name: ${spring.application.name}
    label: master
    profile: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/