spring:
  profiles:
    active: dev
  application:
    name: hello-spring-cloud-web-admin-ribbon
  cloud:
    config:
      uri: http://localhost:8888
      name: ${spring.application.name}
      label: master
      profile: dev
